// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "StaticData/domain"
import mock "github.com/stretchr/testify/mock"

// ClassMemberRepository is an autogenerated mock type for the ClassMemberRepository type
type ClassMemberRepository struct {
	mock.Mock
}

// GetMappingByLabel provides a mock function with given fields: label
func (_m *ClassMemberRepository) GetMappingByLabel(label string) domain.ClassMemberMapping {
	ret := _m.Called(label)

	var r0 domain.ClassMemberMapping
	if rf, ok := ret.Get(0).(func(string) domain.ClassMemberMapping); ok {
		r0 = rf(label)
	} else {
		r0 = ret.Get(0).(domain.ClassMemberMapping)
	}

	return r0
}
